# SHOW DATABASE: HOW MANY DATABASES HAVE IN DB
SHOW DATABASES;

# CREATE A STUDENT DETAILS DATABASE
CREATE DATABASE STUDENT_DETAILS;

# USE DATABASE: OPERATIONS IN DATABASE
USE STUDENT_DETAILS;

# CREATE STUDENT TABLE IN STUDENT DETAILS DATABASE
CREATE TABLE STUDENT(
id INT PRIMARY KEY,
name VARCHAR(255) UNIQUE,
age INT NOT NULL,
addres VARCHAR(255),
dept VARCHAR(255)
);

# INSERT DATA IN STUDENT TABLE
INSERT INTO STUDENT VALUES
(1,'MONIRUL',22,'BANKURA','BCA'),
(2,'SARFARAJ',22,'BANKURA','BA'),
(3,'ARMAN',20,'BANKURA','NURSING');

# DISPLAY ALL DATA FROM STUDENT TABLE
SELECT * FROM STUDENT;

# VIEWS: APPLY ABSTRACT VIEWS IN STUDENT DETAILS
CREATE VIEW custom_view AS SELECT id, name, age FROM STUDENT;

# DISPLAY CUSTOM VIEWS
SELECT * FROM custom_view;

# ALTER VIEWS: CHANGE VIEWS
ALTER VIEW custom_view AS SELECT id,name FROM STUDENT;

# DROP VIEWS: DELETE VIEWS
DROP VIEW IF EXISTS custom_view;






